// Turkish provinces with their İŞKUR page values (plate-based IDs)
export const PROVINCES: { value: string; label: string }[] = [
  { value: '1', label: 'ADANA' },
  { value: '2', label: 'ADIYAMAN' },
  { value: '3', label: 'AFYONKARAHİSAR' },
  { value: '4', label: 'AĞRI' },
  { value: '68', label: 'AKSARAY' },
  { value: '5', label: 'AMASYA' },
  { value: '6', label: 'ANKARA' },
  { value: '7', label: 'ANTALYA' },
  { value: '75', label: 'ARDAHAN' },
  { value: '8', label: 'ARTVİN' },
  { value: '9', label: 'AYDIN' },
  { value: '10', label: 'BALIKESİR' },
  { value: '74', label: 'BARTIN' },
  { value: '72', label: 'BATMAN' },
  { value: '69', label: 'BAYBURT' },
  { value: '11', label: 'BİLECİK' },
  { value: '12', label: 'BİNGÖL' },
  { value: '13', label: 'BİTLİS' },
  { value: '14', label: 'BOLU' },
  { value: '15', label: 'BURDUR' },
  { value: '16', label: 'BURSA' },
  { value: '17', label: 'ÇANAKKALE' },
  { value: '18', label: 'ÇANKIRI' },
  { value: '19', label: 'ÇORUM' },
  { value: '20', label: 'DENİZLİ' },
  { value: '21', label: 'DİYARBAKIR' },
  { value: '81', label: 'DÜZCE' },
  { value: '22', label: 'EDİRNE' },
  { value: '23', label: 'ELAZIĞ' },
  { value: '24', label: 'ERZİNCAN' },
  { value: '25', label: 'ERZURUM' },
  { value: '26', label: 'ESKİŞEHİR' },
  { value: '27', label: 'GAZİANTEP' },
  { value: '28', label: 'GİRESUN' },
  { value: '29', label: 'GÜMÜŞHANE' },
  { value: '30', label: 'HAKKARİ' },
  { value: '31', label: 'HATAY' },
  { value: '76', label: 'IĞDIR' },
  { value: '32', label: 'ISPARTA' },
  { value: '34', label: 'İSTANBUL' },
  { value: '35', label: 'İZMİR' },
  { value: '46', label: 'KAHRAMANMARAŞ' },
  { value: '78', label: 'KARABÜK' },
  { value: '70', label: 'KARAMAN' },
  { value: '36', label: 'KARS' },
  { value: '37', label: 'KASTAMONU' },
  { value: '38', label: 'KAYSERİ' },
  { value: '79', label: 'KİLİS' },
  { value: '71', label: 'KIRIKKALE' },
  { value: '39', label: 'KIRKLARELİ' },
  { value: '40', label: 'KIRŞEHİR' },
  { value: '41', label: 'KOCAELİ' },
  { value: '42', label: 'KONYA' },
  { value: '43', label: 'KÜTAHYA' },
  { value: '44', label: 'MALATYA' },
  { value: '45', label: 'MANİSA' },
  { value: '47', label: 'MARDİN' },
  { value: '33', label: 'MERSİN' },
  { value: '48', label: 'MUĞLA' },
  { value: '49', label: 'MUŞ' },
  { value: '50', label: 'NEVŞEHİR' },
  { value: '51', label: 'NİĞDE' },
  { value: '52', label: 'ORDU' },
  { value: '80', label: 'OSMANİYE' },
  { value: '53', label: 'RİZE' },
  { value: '54', label: 'SAKARYA' },
  { value: '55', label: 'SAMSUN' },
  { value: '56', label: 'SİİRT' },
  { value: '57', label: 'SİNOP' },
  { value: '58', label: 'SİVAS' },
  { value: '63', label: 'ŞANLIURFA' },
  { value: '73', label: 'ŞIRNAK' },
  { value: '59', label: 'TEKİRDAĞ' },
  { value: '60', label: 'TOKAT' },
  { value: '61', label: 'TRABZON' },
  { value: '62', label: 'TUNCELİ' },
  { value: '64', label: 'UŞAK' },
  { value: '65', label: 'VAN' },
  { value: '77', label: 'YALOVA' },
  { value: '66', label: 'YOZGAT' },
  { value: '67', label: 'ZONGULDAK' },
];

// Districts keyed by province value
export const DISTRICTS: Record<string, { value: string; label: string }[]> = {
  '6': [ // ANKARA
    { value: '1', label: 'ALTINDAĞ' }, { value: '2', label: 'AKYURT' }, { value: '3', label: 'AYAŞ' },
    { value: '4', label: 'BALA' }, { value: '5', label: 'BEYPAZARI' }, { value: '6', label: 'ÇAMLIDERE' },
    { value: '7', label: 'ÇANKAYA' }, { value: '8', label: 'ÇUBUK' }, { value: '9', label: 'ELMADAĞ' },
    { value: '10', label: 'ETİMESGUT' }, { value: '11', label: 'EVREN' }, { value: '12', label: 'GÖLBAŞI' },
    { value: '13', label: 'GÜDÜL' }, { value: '14', label: 'HAYMANA' }, { value: '15', label: 'KALECİK' },
    { value: '16', label: 'KAHRAMANKAZAN' }, { value: '17', label: 'KEÇİÖREN' }, { value: '18', label: 'KIZILCAHAMAM' },
    { value: '19', label: 'MAMAK' }, { value: '20', label: 'NALLIHAN' }, { value: '21', label: 'POLATLΙ' },
    { value: '22', label: 'PURSAKLAR' }, { value: '23', label: 'SİNCAN' }, { value: '24', label: 'ŞEREFLİKOÇHİSAR' },
    { value: '25', label: 'YENİMAHALLE' },
  ],
  '34': [ // İSTANBUL
    { value: '1', label: 'ADALAR' }, { value: '2', label: 'ARNAVUTKÖY' }, { value: '3', label: 'ATAŞEHİR' },
    { value: '4', label: 'AVCILAR' }, { value: '5', label: 'BAĞCILAR' }, { value: '6', label: 'BAHÇELİEVLER' },
    { value: '7', label: 'BAKIRKÖY' }, { value: '8', label: 'BAŞAKŞEHİR' }, { value: '9', label: 'BAYRAMPAŞA' },
    { value: '10', label: 'BEŞİKTAŞ' }, { value: '11', label: 'BEYKOZ' }, { value: '12', label: 'BEYLİKDÜZÜ' },
    { value: '13', label: 'BEYOĞLU' }, { value: '14', label: 'BÜYÜKÇEKMECE' }, { value: '15', label: 'ÇATALCA' },
    { value: '16', label: 'ÇEKMEKÖY' }, { value: '17', label: 'ESENLER' }, { value: '18', label: 'ESENYURT' },
    { value: '19', label: 'EYÜPSULTAN' }, { value: '20', label: 'FATİH' }, { value: '21', label: 'GAZİOSMANPAŞA' },
    { value: '22', label: 'GÜNGÖREN' }, { value: '23', label: 'KADIKÖY' }, { value: '24', label: 'KAĞITHANE' },
    { value: '25', label: 'KARTAL' }, { value: '26', label: 'KÜÇÜKÇEKMECE' }, { value: '27', label: 'MALTEPE' },
    { value: '28', label: 'PENDİK' }, { value: '29', label: 'SANCAKTEPE' }, { value: '30', label: 'SARIYER' },
    { value: '31', label: 'SİLİVRİ' }, { value: '32', label: 'SULTANBEYLİ' }, { value: '33', label: 'SULTANGAZİ' },
    { value: '34', label: 'ŞİLE' }, { value: '35', label: 'ŞİŞLİ' }, { value: '36', label: 'TUZLA' },
    { value: '37', label: 'ÜMRANİYE' }, { value: '38', label: 'ÜSKÜDAR' }, { value: '39', label: 'ZEYTİNBURNU' },
  ],
  '35': [ // İZMİR
    { value: '1', label: 'ALİAĞA' }, { value: '2', label: 'BALÇOVA' }, { value: '3', label: 'BAYINDIR' },
    { value: '4', label: 'BAYRAKLI' }, { value: '5', label: 'BERGAMA' }, { value: '6', label: 'BEYDAĞ' },
    { value: '7', label: 'BORNOVA' }, { value: '8', label: 'BUCA' }, { value: '9', label: 'ÇEŞME' },
    { value: '10', label: 'ÇİĞLİ' }, { value: '11', label: 'DİKİLİ' }, { value: '12', label: 'FOÇA' },
    { value: '13', label: 'GAZİEMİR' }, { value: '14', label: 'GÜZELBAHÇE' }, { value: '15', label: 'KARABAĞLAR' },
    { value: '16', label: 'KARABURUN' }, { value: '17', label: 'KARŞIYAKA' }, { value: '18', label: 'KEMALPAŞA' },
    { value: '19', label: 'KINIK' }, { value: '20', label: 'KİRAZ' }, { value: '21', label: 'KONAK' },
    { value: '22', label: 'MENDERES' }, { value: '23', label: 'MENEMEN' }, { value: '24', label: 'NARLIDERE' },
    { value: '25', label: 'ÖDEMİŞ' }, { value: '26', label: 'SEFERİHİSAR' }, { value: '27', label: 'SELÇUK' },
    { value: '28', label: 'TİRE' }, { value: '29', label: 'TORBALI' }, { value: '30', label: 'URLA' },
  ],
  '16': [ // BURSA
    { value: '1', label: 'BÜYÜKORHAN' }, { value: '2', label: 'GEMLİK' }, { value: '3', label: 'GÜRSU' },
    { value: '4', label: 'HARMANCIK' }, { value: '5', label: 'İNEGÖL' }, { value: '6', label: 'İZNİK' },
    { value: '7', label: 'KARACABEY' }, { value: '8', label: 'KELES' }, { value: '9', label: 'KESTEL' },
    { value: '10', label: 'MUDANYA' }, { value: '11', label: 'MUSTAFAKEMALPAŞA' }, { value: '12', label: 'NİLÜFER' },
    { value: '13', label: 'ORHANELİ' }, { value: '14', label: 'ORHANGAZİ' }, { value: '15', label: 'OSMANGAZİ' },
    { value: '16', label: 'YENİŞEHİR' }, { value: '17', label: 'YILDIRIM' },
  ],
  '7': [ // ANTALYA
    { value: '1', label: 'AKSEKİ' }, { value: '2', label: 'AKSU' }, { value: '3', label: 'ALANYA' },
    { value: '4', label: 'DEMRE' }, { value: '5', label: 'DÖŞEMEALTI' }, { value: '6', label: 'ELMALI' },
    { value: '7', label: 'FİNİKE' }, { value: '8', label: 'GAZİPAŞA' }, { value: '9', label: 'GÜNDOĞMUŞ' },
    { value: '10', label: 'İBRADI' }, { value: '11', label: 'KAŞ' }, { value: '12', label: 'KEMER' },
    { value: '13', label: 'KEPEZ' }, { value: '14', label: 'KONYAALTI' }, { value: '15', label: 'KORKUTELİ' },
    { value: '16', label: 'KUMLUCA' }, { value: '17', label: 'MANAVGAT' }, { value: '18', label: 'MURATPAŞA' },
    { value: '19', label: 'SERİK' },
  ],
  '27': [ // GAZİANTEP
    { value: '1', label: 'ARABAN' }, { value: '2', label: 'İSLAHİYE' }, { value: '3', label: 'KARKAMIŞ' },
    { value: '4', label: 'NİZİP' }, { value: '5', label: 'NURDAĞI' }, { value: '6', label: 'OĞUZELİ' },
    { value: '7', label: 'ŞAHİNBEY' }, { value: '8', label: 'ŞEHİTKAMİL' }, { value: '9', label: 'YAVUZELİ' },
  ],
  '1': [ // ADANA
    { value: '1', label: 'ALADAĞ' }, { value: '2', label: 'CEYHAN' }, { value: '3', label: 'ÇUKUROVA' },
    { value: '4', label: 'FEKE' }, { value: '5', label: 'İMAMOĞLU' }, { value: '6', label: 'KARAİSALI' },
    { value: '7', label: 'KARATAŞ' }, { value: '8', label: 'KOZAN' }, { value: '9', label: 'POZANTI' },
    { value: '10', label: 'SAİMBEYLİ' }, { value: '11', label: 'SARIÇAM' }, { value: '12', label: 'SEYHAN' },
    { value: '13', label: 'TUFANBEYLİ' }, { value: '14', label: 'YUMURTALIK' }, { value: '15', label: 'YÜREĞİR' },
  ],
  '33': [ // MERSİN
    { value: '1', label: 'AKDENIZ' }, { value: '2', label: 'ANAMUR' }, { value: '3', label: 'AYDINCIK' },
    { value: '4', label: 'BOZYAZI' }, { value: '5', label: 'ÇAMLIYAYLA' }, { value: '6', label: 'ERDEMLİ' },
    { value: '7', label: 'GÜLNAR' }, { value: '8', label: 'MEZİTLİ' }, { value: '9', label: 'MUT' },
    { value: '10', label: 'SİLİFKE' }, { value: '11', label: 'TARSUS' }, { value: '12', label: 'TOROSLAR' },
    { value: '13', label: 'YENİŞEHİR' },
  ],
  '41': [ // KOCAELİ
    { value: '1', label: 'BAŞİSKELE' }, { value: '2', label: 'ÇAYIROVA' }, { value: '3', label: 'DARICA' },
    { value: '4', label: 'DERİNCE' }, { value: '5', label: 'DİLOVASI' }, { value: '6', label: 'GEBZE' },
    { value: '7', label: 'GÖLCÜK' }, { value: '8', label: 'İZMİT' }, { value: '9', label: 'KANDIRA' },
    { value: '10', label: 'KARAMÜRSEL' }, { value: '11', label: 'KARTEPE' }, { value: '12', label: 'KÖRFEZ' },
  ],
  '42': [ // KONYA
    { value: '1', label: 'AHIRLI' }, { value: '2', label: 'AKÖREN' }, { value: '3', label: 'AKŞEHİR' },
    { value: '4', label: 'ALTINEKİN' }, { value: '5', label: 'BEYŞEHİR' }, { value: '6', label: 'BOZKIR' },
    { value: '7', label: 'CİHANBEYLİ' }, { value: '8', label: 'ÇELTİK' }, { value: '9', label: 'ÇUMRA' },
    { value: '10', label: 'DERBENT' }, { value: '11', label: 'DEREBUCAK' }, { value: '12', label: 'DOĞANHİSAR' },
    { value: '13', label: 'EMİRGAZİ' }, { value: '14', label: 'EREĞLİ' }, { value: '15', label: 'GÜNEYSINIR' },
    { value: '16', label: 'HADİM' }, { value: '17', label: 'HALKAPINAR' }, { value: '18', label: 'HÜYÜK' },
    { value: '19', label: 'ILGIN' }, { value: '20', label: 'KADINHANI' }, { value: '21', label: 'KARAPINAR' },
    { value: '22', label: 'KARATAY' }, { value: '23', label: 'KULU' }, { value: '24', label: 'MERAM' },
    { value: '25', label: 'SARAYÖNÜ' }, { value: '26', label: 'SELÇUKLu' }, { value: '27', label: 'SEYDİŞEHİR' },
    { value: '28', label: 'TAŞKENT' }, { value: '29', label: 'TUZLUKÇU' }, { value: '30', label: 'YALIHÜYÜK' },
    { value: '31', label: 'YUNAK' },
  ],
  '38': [ // KAYSERİ
    { value: '1', label: 'AKKIŞLA' }, { value: '2', label: 'BÜNYAN' }, { value: '3', label: 'DEVELİ' },
    { value: '4', label: 'FELAHİYE' }, { value: '5', label: 'HACILAR' }, { value: '6', label: 'İNCESU' },
    { value: '7', label: 'KOCASİNAN' }, { value: '8', label: 'MELİKGAZİ' }, { value: '9', label: 'ÖZVATAN' },
    { value: '10', label: 'PINARBAŞI' }, { value: '11', label: 'SARIOĞLAN' }, { value: '12', label: 'SARIZ' },
    { value: '13', label: 'TALAS' }, { value: '14', label: 'TOMARZA' }, { value: '15', label: 'YAHYALI' },
    { value: '16', label: 'YEŞİLHİSAR' },
  ],
  '55': [ // SAMSUN
    { value: '1', label: '19 MAYIS' }, { value: '2', label: 'ALAÇAM' }, { value: '3', label: 'ASARCIK' },
    { value: '4', label: 'ATAKUM' }, { value: '5', label: 'AYVACIK' }, { value: '6', label: 'BAFRA' },
    { value: '7', label: 'CANİK' }, { value: '8', label: 'ÇARŞAMBA' }, { value: '9', label: 'HAVZA' },
    { value: '10', label: 'İLKADIM' }, { value: '11', label: 'KAVAK' }, { value: '12', label: 'LADİK' },
    { value: '13', label: 'SALIPAZARI' }, { value: '14', label: 'TEKKEKÖY' }, { value: '15', label: 'TERME' },
    { value: '16', label: 'VEZİRKÖPRÜ' }, { value: '17', label: 'YAKAKENT' },
  ],
  '61': [ // TRABZON
    { value: '1', label: 'AKÇAABAT' }, { value: '2', label: 'ARAKLΙ' }, { value: '3', label: 'ARSİN' },
    { value: '4', label: 'BEŞİKDÜZÜ' }, { value: '5', label: 'ÇARŞIBAŞI' }, { value: '6', label: 'ÇAYKARA' },
    { value: '7', label: 'DERNEKPAZARI' }, { value: '8', label: 'DÜZKÖY' }, { value: '9', label: 'HAYRAT' },
    { value: '10', label: 'KÖPRÜBAŞI' }, { value: '11', label: 'MAÇKA' }, { value: '12', label: 'OF' },
    { value: '13', label: 'ORTAHİSAR' }, { value: '14', label: 'SÜRMENE' }, { value: '15', label: 'ŞALPAZARI' },
    { value: '16', label: 'TONYA' }, { value: '17', label: 'VAKFIKEBİR' }, { value: '18', label: 'YOMRA' },
  ],
  '21': [ // DİYARBAKIR
    { value: '1', label: 'BAĞLAR' }, { value: '2', label: 'BİSMİL' }, { value: '3', label: 'ÇERMİK' },
    { value: '4', label: 'ÇINAR' }, { value: '5', label: 'ÇÜNGÜŞ' }, { value: '6', label: 'DİCLE' },
    { value: '7', label: 'EĞİL' }, { value: '8', label: 'ERGANİ' }, { value: '9', label: 'HANİ' },
    { value: '10', label: 'HAZRO' }, { value: '11', label: 'KAYAPINAR' }, { value: '12', label: 'KOCAKÖY' },
    { value: '13', label: 'KULP' }, { value: '14', label: 'LİCE' }, { value: '15', label: 'SİLVAN' },
    { value: '16', label: 'SUR' }, { value: '17', label: 'YENİŞEHİR' },
  ],
  '63': [ // ŞANLIURFA
    { value: '1', label: 'AKÇAKALE' }, { value: '2', label: 'BİRECİK' }, { value: '3', label: 'BOZOVA' },
    { value: '4', label: 'CEYLANPINAR' }, { value: '5', label: 'EYYÜBİYE' }, { value: '6', label: 'HALİLİYE' },
    { value: '7', label: 'HARRAN' }, { value: '8', label: 'HİLVAN' }, { value: '9', label: 'KARAKÖPRÜ' },
    { value: '10', label: 'SİVEREK' }, { value: '11', label: 'SURUÇ' }, { value: '12', label: 'VİRANŞEHİR' },
  ],
  '31': [ // HATAY
    { value: '1', label: 'ALTINÖZÜ' }, { value: '2', label: 'ANTAKYA' }, { value: '3', label: 'ARSUZ' },
    { value: '4', label: 'BELEN' }, { value: '5', label: 'DEFNE' }, { value: '6', label: 'DÖRTYOL' },
    { value: '7', label: 'ERZİN' }, { value: '8', label: 'HASSA' }, { value: '9', label: 'İSKENDERUN' },
    { value: '10', label: 'KIRIKHAN' }, { value: '11', label: 'KUMLU' }, { value: '12', label: 'PAYAS' },
    { value: '13', label: 'REYHANLI' }, { value: '14', label: 'SAMANDAĞ' }, { value: '15', label: 'YAYLADAĞI' },
  ],
  '54': [ // SAKARYA
    { value: '1', label: 'ADAPAZARI' }, { value: '2', label: 'AKYAZI' }, { value: '3', label: 'ARİFİYE' },
    { value: '4', label: 'ERENLER' }, { value: '5', label: 'FERİZLİ' }, { value: '6', label: 'GEYVE' },
    { value: '7', label: 'HENDEK' }, { value: '8', label: 'KARAAPELİT' }, { value: '9', label: 'KARASU' },
    { value: '10', label: 'KAYNARCA' }, { value: '11', label: 'KOCAALİ' }, { value: '12', label: 'PAMUKOVA' },
    { value: '13', label: 'SAPANCA' }, { value: '14', label: 'SERDİVAN' }, { value: '15', label: 'SÖĞÜTLÜ' },
    { value: '16', label: 'TARAKLΙ' },
  ],
  '59': [ // TEKİRDAĞ
    { value: '1', label: 'ÇERKEZKÖY' }, { value: '2', label: 'ÇORLU' }, { value: '3', label: 'ERGENE' },
    { value: '4', label: 'HAYRABOLU' }, { value: '5', label: 'KAPAKLI' }, { value: '6', label: 'MALKARA' },
    { value: '7', label: 'MARMARAEREĞLISI' }, { value: '8', label: 'MURATLI' }, { value: '9', label: 'SARAY' },
    { value: '10', label: 'SÜLEYMANPAŞA' }, { value: '11', label: 'ŞARKÖY' },
  ],
  '10': [ // BALIKESİR
    { value: '1', label: 'ALTIEYLÜL' }, { value: '2', label: 'AYVALIK' }, { value: '3', label: 'BALYA' },
    { value: '4', label: 'BANDIRMA' }, { value: '5', label: 'BİGADİÇ' }, { value: '6', label: 'BURHANİYE' },
    { value: '7', label: 'DURSUNBEY' }, { value: '8', label: 'EDREMİT' }, { value: '9', label: 'ERDEK' },
    { value: '10', label: 'GÖMEÇ' }, { value: '11', label: 'GÖNEN' }, { value: '12', label: 'HAVRAN' },
    { value: '13', label: 'İVRİNDİ' }, { value: '14', label: 'KARESİ' }, { value: '15', label: 'KEPSUT' },
    { value: '16', label: 'MANYAS' }, { value: '17', label: 'MARMARA' }, { value: '18', label: 'SAVAŞTEPE' },
    { value: '19', label: 'SINDIRGI' }, { value: '20', label: 'SUSURLUK' },
  ],
  '45': [ // MANİSA
    { value: '1', label: 'AHMETLİ' }, { value: '2', label: 'AKHİSAR' }, { value: '3', label: 'ALAŞEHİR' },
    { value: '4', label: 'DEMİRCİ' }, { value: '5', label: 'GÖLMARMARA' }, { value: '6', label: 'GÖRDES' },
    { value: '7', label: 'KIRKAĞAÇ' }, { value: '8', label: 'KÖPRÜBAŞI' }, { value: '9', label: 'KULA' },
    { value: '10', label: 'SALİHLİ' }, { value: '11', label: 'SARIGÖL' }, { value: '12', label: 'SARUHANLI' },
    { value: '13', label: 'SELENDİ' }, { value: '14', label: 'SOMA' }, { value: '15', label: 'ŞEHZADELER' },
    { value: '16', label: 'TURGUTLU' }, { value: '17', label: 'YUNUSEMRE' },
  ],
  '20': [ // DENİZLİ
    { value: '1', label: 'ACIPAYAM' }, { value: '2', label: 'BABADAĞ' }, { value: '3', label: 'BAKLAN' },
    { value: '4', label: 'BEKİLLİ' }, { value: '5', label: 'BEYAĞAÇ' }, { value: '6', label: 'BOZKURT' },
    { value: '7', label: 'BULDAN' }, { value: '8', label: 'ÇAL' }, { value: '9', label: 'ÇAMELİ' },
    { value: '10', label: 'ÇARDAK' }, { value: '11', label: 'ÇİVRİL' }, { value: '12', label: 'GÜNEY' },
    { value: '13', label: 'HONAZ' }, { value: '14', label: 'KALE' }, { value: '15', label: 'MERKEZEFENDİ' },
    { value: '16', label: 'PAMUKKALE' }, { value: '17', label: 'SARAYKÖY' }, { value: '18', label: 'SERİNHİSAR' },
    { value: '19', label: 'TAVAS' },
  ],
  '22': [ // EDİRNE
    { value: '1', label: 'EDİRNE MERKEZ' }, { value: '2', label: 'ENEZ' }, { value: '3', label: 'HAVSA' },
    { value: '4', label: 'İPSALA' }, { value: '5', label: 'KEŞAN' }, { value: '6', label: 'LALAPAŞA' },
    { value: '7', label: 'MERİÇ' }, { value: '8', label: 'SÜLOĞLU' }, { value: '9', label: 'UZUNKÖPRÜ' },
  ],
  '17': [ // ÇANAKKALE
    { value: '1', label: 'AYVACIK' }, { value: '2', label: 'BAYRAMİÇ' }, { value: '3', label: 'BİGA' },
    { value: '4', label: 'BOZCAADA' }, { value: '5', label: 'ÇAN' }, { value: '6', label: 'ÇANAKKALE MERKEZ' },
    { value: '7', label: 'ECEABAT' }, { value: '8', label: 'EZİNE' }, { value: '9', label: 'GELİBOLU' },
    { value: '10', label: 'GÖKÇEADA' }, { value: '11', label: 'LAPSEKİ' }, { value: '12', label: 'YENİCE' },
  ],
};
